In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.DataFrame([[1,2,3,4],[1,2,3,4],[1,2,5,6],[3,2,5,7],[7,2,5,6]])
df

   0  1  2  3
0  1  2  3  4
1  1  2  3  4
2  1  2  5  6
3  3  2  5  7
4  7  2  5  6

In [4]:
df.duplicated()

0    False
1     True
2    False
3    False
4    False
dtype: bool

In [6]:
df.duplicated().sum()

1

In [15]:
df.duplicated(subset=2).sum()

0    False
1     True
2    False
3     True
4     True
dtype: bool

In [8]:
df.duplicated(subset=[2,3]).sum()

2

In [9]:
df.drop_duplicates()

   0  1  2  3
0  1  2  3  4
2  1  2  5  6
3  3  2  5  7
4  7  2  5  6

In [12]:
df.drop_duplicates(keep='last',subset=0)
# by default keeps 1st and drops the last

   0  1  2  3
2  1  2  5  6
3  3  2  5  7
4  7  2  5  6

In [14]:
df.drop_duplicates(keep=False)
# removes all the duplicate values even the original ones

   0  1  2  3
2  1  2  5  6
3  3  2  5  7
4  7  2  5  6